---
server:
  error:
    whitelabel:
      enabled=false:

spring:
  config:
    activate:
      on-profile: file
logging:
  level:
    org:
      springframework: warn

voucher.path: "./VoucherList.csv"


---
server:
  error:
    whitelabel:
      enabled=false:

spring:
  config:
    activate:
      on-profile: memory
logging:
  level:
    org:
      springframework: warn

voucher.path: "./VoucherList.csv"
---

