---
spring:
  config:
    activate:
      on-profile: file
logging:
  level:
    org:
      springframework: warn

voucher.path: "./VoucherList.csv"

---
spring:
  config:
    activate:
      on-profile: memory
logging:
  level:
    org:
      springframework: warn

voucher.path: "./VoucherList.csv"
---

