spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order_mgmt
    username: root
    password: 1234567890
logging:
  level:
    org:
      springframework: warn
voucher.path: "./VoucherList.csv"